### ISSUE TITLE
How to more easily generate app configs?

### ISSUE THREAD

**Issue by boredsquirrel** [ImranR98/apps.obtainium.imranr.dev#130]
In Obtainium, if I click on an app and "share app configuration as HTML" I can share a link that opens Obtainium and extracts the JSON metadata correctly.

I have 150 Apps, how could this be done more easily so that I can add my apps to the App list here?

**Comment by Hamster45105** [comment]
> You can auto-generate config files from an Obtainium export by running node generateFromExport.js <path to Obtainium export>

Although before contributing such a large amount of apps, please be aware of [this comment](https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/84#discussioncomment-9717730) and try to keep that in mind.

**Comment by Hamster45105** [comment]
In addition, to generate a single config from an app config URL you can use [this Python script](https://github.com/ImranR98/apps.obtainium.imranr.dev/blob/main/generate_from_url.py).

**Comment by boredsquirrel** [comment]
Thanks! An issue is that the Obtainium share URL contains tons of data that is the default value. But this is a different issue. I will use that and already got all the share URLs

**Comment by Hamster45105** [comment]
If that's all you need to know, could you please close this issue?

**Comment by boredsquirrel** [comment]
I did not yet do it. These export URLs contain all the configs no matter if they are default. If it works anyways I can close this.

**Comment by boredsquirrel** [comment]
works really well!
