### ISSUE TITLE
Website Build Failed

### ISSUE THREAD

**Issue by Hamster45105** [ImranR98/apps.obtainium.imranr.dev#133]
Since commit https://github.com/ImranR98/apps.obtainium.imranr.dev/commit/639cfacabd3bca4d1e77a0bc0ecdd994f1a144f5 the website has failed to build

**Comment by DwainZwerg** [comment]
Fix attempted https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/135

**Comment by Hamster45105** [comment]
That seemed to fix it!
