### ISSUE TITLE
[Question] Will this scale?

### ISSUE THREAD

**Issue by Mikaela** [ImranR98/apps.obtainium.imranr.dev#14]
I am wondering how scalable is this project if everyone is supposed to edit the same `data.json` and will there be merge conflicts due to it? There are already some commits that add or remove the last line change at the end of file.

I would add [pre-commit](https://pre-commit.com) and [pre-commit ci](https://pre-commit.ci) as a first-aid to keep unified formatting, but I don't know how far that would carry to help.

**Comment by ImranR98** [comment]
You're right - there would probably be scaling issues. Maybe it makes sense to use separate JSON files per app?

**Comment by Mikaela** [comment]
Some sort of alphabetical sorting is available through the `pretty-format-json` pre-commit hook if it was uncommented e.g.

- https://github.com/ImranR98/apps.obtainium.imranr.dev/compare/main...Mikaela:apps.obtainium.imranr.dev:pre-commit2?expand=1

Enforcing it would be a matter of enabling https://pre-commit.ci for the repository.

-----

However regardless of this option, I still have more faith in scalability of individual json files (as evinced by projects using git for repositories such as the aforementioned homebrew), while I don't know how far that will scale either while still being contributor-friendly. I suspect having subdirectories for different categories might help as well, but that brings new problem of apps being able to belong to multiple categories?

**Comment by ImranR98** [comment]
I've split the data into separate files. Not sure we need alphabetical ordering given the complexity it adds (if anyone wants to modify a given app file, they can sort by A-Z or Ctrl-F in any file manager anyways - they are named by app ID).
