### ISSUE TITLE
[Enhancement]Please add the market on https://imranr.dev/#projects

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/apps.obtainium.imranr.dev#16]
Hello @ImranR98 ,
I would like to suggest that you add a link to the subpage https://apps.obtainium.imranr.dev/ labelled "Market" or similar to the Obtainium links on [your main page](https://imranr.dev/#projects).
Thanks for the great app,
Dwain

**Comment by ImranR98** [comment]
Hmm, not sure I want to at this point, maybe in the future.
