### ISSUE TITLE
No way to access homepage from redirect page

### ISSUE THREAD

**Issue by catthou** [ImranR98/apps.obtainium.imranr.dev#18]
A redirect page such as:
https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22dev.patrickgold.florisboard.beta%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fflorisboard%2Fflorisboard%22%2C%22author%22%3A%22florisboard%22%2C%22name%22%3A%22FlorisBoard%20Beta%22%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Atrue%7D%22%7D
...has no way to get to the main page of the project to browse for other app links.

I think this is a problem because someone might be sent a link like the above from a friend or another website, and want to investigate what this apps list is about - but they'll have no obvious way to do so without guessing that they can edit the url.

A header at the top to take you back to the main page is one solution, or a link at the bottom with text like, "This link was contributed to apps.obtainium.imranr.dev by the community."

**Comment by ImranR98** [comment]
Added
