### ISSUE TITLE
Use app version release date as the version for Firefox Nightly

### ISSUE THREAD

**Issue by ghost** [ImranR98/apps.obtainium.imranr.dev#205]
Firefox Nightly updates daily and the app's version name remains the same unless it's a new major release so the app version's release date should be used as the version.

**Comment by DwainZwerg** [comment]
I use the config I added to the store myself and everything works for me (at least one update every day). What is the problem for you?

**Comment by DwainZwerg** [comment]
Yes, it works. Great! I'll change it in the config right away! Thank you very much!

**Comment by DwainZwerg** [comment]
PR was added: https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/219. Can you please mark this issue as done?
