### ISSUE TITLE
Modify "Request Apps" Button to Reduce Spam

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/apps.obtainium.imranr.dev#212]
1. Change wording to spell out exactly what an "easy to add" app is. Something like "if the app can be added to Obtainium in one click after entering it's it's source link (leaving all other settings as default)..."
2. Tell the user what their post should contain (a link to the app repo at minimum).
3. Add a checkbox that should be ticked before the link is enabled.

People can always just bypass all that and come to GitHub directly, but hopefully a checkbox will help reduce nonsense posts. If not, it might be worth looking at open source CAPTCHA alternatives.

**Comment by Hamster45105** [comment]
> People can always just bypass all that and come to GitHub directly, but hopefully a checkbox will help reduce nonsense posts. If not, it might be worth looking at open source CAPTCHA alternatives.

I wonder if it's automated bots spamming or people manually creating silly requests. If people are manually creating the discussions, I'm not sure a CAPTCHA/checkbox would really stop anything.
