### ISSUE TITLE
Big video messed up during transcoding?

### ISSUE THREAD

**Issue by DeMoN100** [ImranR98/apps.obtainium.imranr.dev#213]
Hi I used this to crop a video that was almost 2 hours long & 5GB it was a screen recording I cropped the black edges. After the video finish transcoding it became unplayable & I wasn't able to use it. It was a .mp4 video.

**Comment by ImranR98** [comment]
Not related to this app.

**Comment by DeMoN100** [comment]
> Not related to this app.

Yes it is because it's the app that did it. How are you not going to look into whats possibly an encoding issue with your app. Have you tried a 2 hour video before in an mp4 format? The video was fine before I ran it through your app.

**Comment by ImranR98** [comment]
You're commenting in the wrong place. I'm guessing you're having trouble with some kind of video editor that you installed through Obtainium? This repo is for Obtainium, not whatever app you were using.

**Comment by DeMoN100** [comment]
My apologizes I didn't realize I was in the wrong repo.
