### ISSUE TITLE
FUTO Voice Input

### ISSUE THREAD

**Issue by b-risk** [ImranR98/apps.obtainium.imranr.dev#239]
Grayjay and FUTO Keyboard seem to be listed but not the standalone [voice input](https://voiceinput.futo.org/).

**Comment by Hamster45105** [comment]
This is the wrong place to put this. It is meant to go in [app requests](https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/new?category=app-requests).

**Comment by ImranR98** [comment]
This is a simple config - the user just has to enter the URL, no settings changes are necessary. So it wouldn't be added to the site. Even the keyboard and Grayjay are simple and wouldn't have been added today, I added them when the criteria for adding apps was not figured out (while testing the "export JSON to site entry" feature.

**Comment by b-risk** [comment]
> This is a simple config - the user just has to enter the URL, no settings changes are necessary. So it wouldn't be added to the site. Even the keyboard and Grayjay are simple and wouldn't have been added today, I added them when the criteria for adding apps was not figured out (while testing the "export JSON to site entry" feature.

I didn't know there was a criteria, thanks for letting me know.

**Comment by DwainZwerg** [comment]
![Screenshot (76)](https://github.com/user-attachments/assets/cb4291ed-7dc7-49b2-ab6a-6e8f557ccb43)
…

**Comment by b-risk** [comment]
Must have missed that part, apologizes.
