### ISSUE TITLE
Firefox broken

### ISSUE THREAD

**Issue by Poolitzer** [ImranR98/apps.obtainium.imranr.dev#248]
Hi, trying to install firefox, I get "Unexpected Error RangeError (start): Invalid value: Not in inclusive range 0..1:-1".

Maybe someone knowledgeable can fix it, or tell me where I went wrong.

**Comment by asininemonkey** [comment]
Same error here. 😐

**Comment by DwainZwerg** [comment]
Are you using my new Config on the Config website? Then this comment should help you: https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/231#issuecomment-2395068810

**Comment by DwainZwerg** [comment]
fixed with https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/259

**Comment by DwainZwerg** [comment]
@Poolitzer @asininemonkey The configuration has been updated. If you add Firefox now, it should work again. Can you close this issue as resolved?

**Comment by asininemonkey** [comment]
Can confirm the revised configuration works again. Just installed the latest point update without issue.
