### ISSUE TITLE
Mullvad VPN configuration not working

### ISSUE THREAD

**Issue by o101010** [ImranR98/apps.obtainium.imranr.dev#25]
Hi,

I tried to install Mullvad VPN from the proposed configuration file but it don't work. I also tried to create one myself on the Obtainium app but I failed. I always receive an error "Could not find a suitable release" .
Same think if I uncheck APK by CPU architecture filter.

Maybe can you correct the config file yourself or remove it ?

PS : I discover this app list accidentally. Maybe it's not enough highlighted on the main Obtainium repo ?

Regards,

**Comment by Hamster45105** [comment]
I've updated the config file, however here is how you can add it to Obtainium now (as mentioned in https://github.com/ImranR98/Obtainium/issues/1276#issuecomment-1900331754):

1. Add the URL: `https://mullvad.net/en/download/vpn/android` for the HTML source
2. Set the link filter to `latest$`.
