### ISSUE TITLE
How to use Telegram as a Source

### ISSUE THREAD

**Issue by KScheid** [ImranR98/apps.obtainium.imranr.dev#286]
I have scoured the README. there is no info on how to add telegram as a source, I'm trying to add a Telegram group as a source.  They post the APK updates in there as well as links to Mediafire. I cannot get Obtanium to locate the APK's. Can someone help?

**Comment by ImranR98** [comment]
Not currently supported. See issue: https://github.com/ImranR98/Obtainium/issues/1
