### ISSUE TITLE
"Reconcile version number" reset & apparently not exported

### ISSUE THREAD

**Issue by inflationsbereinigt** [ImranR98/apps.obtainium.imranr.dev#295]
In Obtainium 1.1.28, it appears that the option "Reconcile version number" is

a) not exported into the HTML link and

b) always reset when opening the app configuration screen to change something

**Comment by Hamster45105** [comment]
This is not the correct place to open this.  Please open an issue on [Obtainium](https://github.com/ImranR98/Obtainium) instead. This issue tracker is for the config website only.
