### ISSUE TITLE
Put a link to you deployed website into the README

### ISSUE THREAD

**Issue by mfbehrens99** [ImranR98/apps.obtainium.imranr.dev#30]
Maybe I am stupid, but it wasn't obvious to me that this project is a website. Would be nice to add a link. I can do a PR next week if someone else did not fix it earlier.

**Comment by Hamster45105** [comment]
You can find a link on the side of the page:

![image](https://github.com/ImranR98/apps.obtainium.imranr.dev/assets/133548095/461d699f-971e-4be2-b764-930299f7442f)

However, I have opened a PR to add the link to the README

**Comment by mfbehrens99** [comment]
I agree, but it was not that obvious on mobile. Thank you looks good
