### ISSUE TITLE
XAPK SUPPORT

### ISSUE THREAD

**Issue by mobsenpai** [ImranR98/apps.obtainium.imranr.dev#316]
### Discussed in https://github.com/ImranR98/apps.obtainium.imranr.dev/discussions/315

<div type='discussions-op-text'>

<sup>Originally posted by **mobsenpai** November 10, 2024</sup>
There source are supported - apkpure and uptodown but I am not able to install this particular app. Is there any way?</div>

**Comment by ImranR98** [comment]
There is already an open issue for XAPK support on the main Obtainium repo. Also you should make sure it really is an XAPK issue and not just that the sites are giving you an incompatible file (try manually downloading/installing from the sites directly).
