### ISSUE TITLE
Make https://obtainium.imranr.dev/ open-source

### ISSUE THREAD

**Issue by DwainZwerg** [ImranR98/apps.obtainium.imranr.dev#320]
With other apps (K-9 Mail, Organic Maps, …) it is common for the project website to be published as a repository on GitHub. I don't expect any major suggestions for changes from anyone, but it is verifiable and otherwise simply common practice. Or is the website already integrated into this repository?

**Comment by ImranR98** [comment]
Done: https://github.com/ImranR98/obtainium.imranr.dev
