### ISSUE TITLE
MiXplorer now proposes multiple architectures

### ISSUE THREAD

**Issue by wyndon** [ImranR98/apps.obtainium.imranr.dev#325]
Thus the current configuration always pulls the first one, which is built for x64. https://mixplorer.com/beta/

**Comment by DarkCrypt** [comment]
Config for arm64:
Import App -> [MiXplorer (Beta)](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.mixplorer.beta%22%2C%22url%22%3A%22https%3A%2F%2Fmixplorer.com%2Fbeta%2F%22%2C%22author%22%3A%22mixplorer.com%22%2C%22name%22%3A%22MiXplorer%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22arm64%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22MiXplorer%20(Beta)%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22A%20file%20manager%20app%20for%20Android%20devices%2C%20offering%20advanced%20features%20such%20as%20root%20access%2C%20cloud%20storage%20integration%2C%20and%20customization%20options.%5C%22%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D)

- Version String Extraction ReGex: `[0-9]+\.[0-9]+\.[0-9]+`
- Filter APKs by Regular Expression: `arm64`

@DwainZwerg or @Hamster45105
The config on the website also needs version extraction.

**Comment by Hamster45105** [comment]
> @DwainZwerg or @Hamster45105 The config on the website also needs version extraction.

Done: https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/326
