### ISSUE TITLE
How to add new apps

### ISSUE THREAD

**Issue by rimaout** [ImranR98/apps.obtainium.imranr.dev#34]
Hey there,

I'm looking to add some new apps to the project. I've got a couple of questions though:

1. How do I figure out the `id` for the app I want to add? 
2. Is there a quick way to the get the `additionalSettings` from  my app, or do I need to manually find and set these?

Any help would be much appreciated!

Thanks!

**Comment by DwainZwerg** [comment]
>     1. How do I figure out the `id` for the app I want to add?

It is the AppID of the operating system. Good file managers that display apps can display this. Alternatively, you can also search for the configuration file in Android/data/dev.imranr.obtainium/files.

>     2. Is there a quick way to the get the `additionalSettings` from  my app, or do I need to manually find and set these?

I always copy the configs from Android/data/dev.imranr.obtainium/files.

**Comment by ImranR98** [comment]
Closing - @DwainZwerg's answers are right. Note you might also be able to see an app's ID in the Android settings (Settings -> Apps -> <App Name>) depending on the OS (GrapheneOS has this).
