### ISSUE TITLE
Nova Launcher Beta

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/apps.obtainium.imranr.dev#46]
https://novalauncher.com/beta 

They share their beta apks here, but I struggled to make it work with Obtainium. Requesting help.

**Comment by prirai** [comment]
> They share their beta apks here, but I struggled to make it work with Obtainium. Requesting help.

Try this direct link:
https://teslacoilapps.com/tesladirect/download.pl?packageName=com.teslacoilsw.launcher&betaType=public

Also, as of writing this comment, the download server seems to be down.

**Comment by LightWayUp** [comment]
With the above changes, Nova Launcher (/Beta) could be installed with Obtainium 🎉!
