### ISSUE TITLE
Thoughts on "Track Only" config contributions?

### ISSUE THREAD

**Issue by RJNY** [ImranR98/apps.obtainium.imranr.dev#58]
Hello 👋 

Curious how you feel about adding "Track Only" sources to your list?

For example:
- [Nether SX2 Patch](https://github.com/Trixarian/NetherSX2-patch)
- [Turnip Drivers](https://github.com/K11MCH1/AdrenoToolsDrivers)

Both are technically under the "Emulation" category, but I don't see any "Track Only" app configurations that exist currently.

**Comment by ImranR98** [comment]
Not sure if it's a good idea. This site is likely to be more useful to people who don't want to or can't mess with config settings. Unless there's a way to clearly indicate that an app is track-only (and make sure the user knows what that means), it could be confusing.
