### ISSUE TITLE
Droidsound-e

### ISSUE THREAD

**Issue by AdityaMH** [ImranR98/apps.obtainium.imranr.dev#62]
https://droidsound-e.web.app/

They share their update here via dropbox, but I struggled to make it work with Obtainium. Requesting help.

**Comment by DwainZwerg** [comment]
We can't help you with that. The releases on https://droidsound-e.web.app/ are loaded via JavaScript, so that Obtainium can't scrape them.

**Comment by Timse93** [comment]
It all in the https://droidsound-e.web.app/version.json
Here's a link to [add to Obtainium](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.droidmjt.droidsounde%22%2C%22url%22%3A%22https%3A%2F%2Fdroidsound-e.web.app%2Fversion.json%22%2C%22author%22%3A%22droidsound-e.web.app%22%2C%22name%22%3A%22App%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Atrue%2C%5C%22versionExtractWholePage%5C%22%3Atrue%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%5C%5C%22version%5C%5C%5C%22%3A%20%5C%5C%5C%22(.%2B%3F)%5C%5C%5C%22%2C%20%5C%5C%5C%22release_date%5C%5C%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%241%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22droidsounde.%2Bbit%5C%5C%5C%5C.apk%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22DroidSound-E%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Android%20chipmusic%20player%5C%22%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3Anull%7D)

**Comment by AdityaMH** [comment]
Thanks a lot! how you got that json?

**Comment by AdityaMH** [comment]
Thanks a lot! how you got that json?

**Comment by Timse93** [comment]
Viewed the page source, the JavaScript does fetch("version.json")
